version: "3.8"
services:
  tonvalidator:
    image: tonvalidator:latest
    build: 
      context: ./validator
      args:
        HOST_TON_USER_ID: ${HOST_TON_USER_ID}
        HOST_TON_GROUP_ID: ${HOST_TON_GROUP_ID}
        TON_SCRIPTS_REV: 'f796da157d9741a12ec7ee2ca929fe2c18e46a73'
    ports:
      - "127.0.0.1:43679:43679"
      - "127.0.0.1:43678:43678"
      - "127.0.0.1:3030:${TON_VALIDATOR_PORT}"
    volumes:
      - type: bind
        source: ${TON_WORK_DIR}
        target: /var/ton-work-${TON_ENV}
      - type: volume
        source: validator-client-keys
        target: /var/ton-client-keys-${TON_ENV}
    environment:
      - TON_ENV=${TON_ENV}
      - TON_VALIDATOR_CONFIG_URL=${TON_VALIDATOR_CONFIG_URL}
      - HOST_TON_CONTROL_USER_ID=${HOST_TON_CONTROL_USER_ID}  # validator will grant perms for client key to this uid
      - HOST_TON_CONTROL_GROUP_ID=${HOST_TON_CONTROL_GROUP_ID}
  tonlogstash:
    image: tonlogstash:latest
    build: 
      context: ./logstash
      args:
        TON_USER_GID: ${HOST_TON_GROUP_ID}
    volumes:
      - type: bind
        source: ${TON_WORK_DIR}/${TON_ENV}
        target: /var/ton-work
      - type: bind
        source: ${TON_CONTROL_WORK_DIR}
        target: /var/ton-control
    environment:
      - TON_LOG_DIR=/var/ton-work/log
      - TON_CONTROL_LOG_DIR=/var/ton-control/log
  toncontrol:
    image: toncontrol:latest
    build:
      context: ..
      dockerfile: docker/toncontrol/Dockerfile
      args:
        HOST_TON_CONTROL_USER_ID: ${HOST_TON_CONTROL_USER_ID}
        HOST_TON_CONTROL_GROUP_ID: ${HOST_TON_CONTROL_GROUP_ID}
    volumes:
      - type: volume
        source: validator-client-keys
        target: /var/ton-keys
      - type: volume
        source: ton-control-keys
        target: /var/ton-control-keys
      # logs will be written under here, data from here will be copied over to /var/ton-keys on start
      - type: bind
        source: ${TON_CONTROL_WORK_DIR}
        target: /var/ton-control
    environment:
      - TON_ENV=${TON_ENV}
      - TON_VALIDATOR_PORT=${TON_VALIDATOR_PORT}
      - TON_VALIDATOR_NETWORK_ADDR=tonvalidator:${TON_VALIDATOR_PORT}
      - TON_CONTROL_SECRET_MANAGER_CONNECTION_STRING=${TON_CONTROL_SECRET_MANAGER_CONNECTION_STRING}
      - TONOS_CLI_CONFIG_URL=https://${TON_ENV}

volumes:
  ton-control-keys:
  validator-client-keys: 
