version: "3.8"
services:
  tonvalidator:
    image: tonvalidator:latest
    restart: always
    build: 
      context: ./validator
      args:
        HOST_TON_USER_ID: ${HOST_TON_USER_ID}
        HOST_TON_GROUP_ID: ${HOST_TON_GROUP_ID}
        TON_BUILD_SCRIPTS_URL: ${TON_BUILD_SCRIPTS_URL}
        TON_BUILD_SCRIPTS_REV: ${TON_BUILD_SCRIPTS_REV}
    ports:
      - "30310:30310"
      - "30310:30310/udp"
      - "127.0.0.1:3030:3030"
    volumes:
      - type: bind
        source: ${TON_WORK_DIR}
        target: /var/ton-work-${TON_ENV}
        consistency: delegated
      - type: volume
        source: validator-client-keys
        target: /var/ton-client-keys-${TON_ENV}
    environment:
      - TON_ENV=${TON_ENV}
      - TON_VALIDATOR_CONFIG_URL=${TON_VALIDATOR_CONFIG_URL}
      - HOST_TON_CONTROL_USER_ID=${HOST_TON_CONTROL_USER_ID}  # validator will grant perms for client key to this uid
      - HOST_TON_CONTROL_GROUP_ID=${HOST_TON_CONTROL_GROUP_ID}
  tonlogstash:
    image: tonlogstash:latest
    restart: on-failure
    build: 
      context: ./logstash
      args:
        TON_USER_GID: ${HOST_TON_GROUP_ID}
    volumes:
      - type: bind
        source: ${TON_WORK_DIR}
        target: /var/ton-work
      - type: bind
        source: ${TON_CONTROL_WORK_DIR}
        target: /var/ton-control
    environment:
      - TON_ENV=${TON_ENV}
      - TON_WORK_DIR=/var/ton-work
      - TON_CONTROL_WORK_DIR=/var/ton-control
      - TON_LOG_DIR=/var/ton-work/${TON_ENV}/log
      - TON_CONTROL_LOG_DIR=/var/ton-control/${TON_ENV}/log
  toncontrol:
    image: toncontrol:latest
    restart: always
    build:
      context: ..
      dockerfile: docker/toncontrol/Dockerfile
      args:
        HOST_TON_CONTROL_USER_ID: ${HOST_TON_CONTROL_USER_ID}
        HOST_TON_CONTROL_GROUP_ID: ${HOST_TON_CONTROL_GROUP_ID}
    volumes:
      - type: volume
        source: validator-client-keys
        target: /var/ton-keys
      - type: volume
        source: ton-control-keys
        target: /var/ton-control-keys
      # logs will be written under here, data from here will be copied over to /var/ton-keys on start
      - type: bind
        source: ${TON_CONTROL_WORK_DIR}
        target: /var/ton-control
    environment:
      - TON_ENV=${TON_ENV}
      - TON_CONTROL_VALIDATOR_NETWORK_ADDR=${TON_CONTROL_VALIDATOR_NETWORK_ADDR}
      - TON_CONTROL_VALIDATOR_LITE_CLIENT_ADDR=${TON_CONTROL_VALIDATOR_LITE_CLIENT_ADDR}
      - TON_CONTROL_QUEUE_NAME=${TON_CONTROL_QUEUE_NAME}
      - TON_CONTROL_SECRET_MANAGER_CONNECTION_STRING=${TON_CONTROL_SECRET_MANAGER_CONNECTION_STRING}
      - TON_CONTROL_SKIP_ELECTIONS=${TON_CONTROL_SKIP_ELECTIONS}
      - TONOS_CLI_CONFIG_URL=${TONOS_CLI_CONFIG_URL}
      - TON_CONTROL_DEFAULT_STAKE=${TON_CONTROL_DEFAULT_STAKE}
      - TON_CONTROL_STAKE_MAX_FACTOR=${TON_CONTROL_STAKE_MAX_FACTOR}
      - TON_CONTROL_CLIENT_KEY_PATH=${TON_CONTROL_CLIENT_KEY_PATH}
      - TON_CONTROL_SERVER_PUB_KEY_PATH=${TON_CONTROL_SERVER_PUB_KEY_PATH}
      - TON_CONTROL_LITE_SERVER_PUB_KEY_PATH=${TON_CONTROL_LITE_SERVER_PUB_KEY_PATH}

volumes:
  ton-control-keys:
  validator-client-keys: 
