# Scan this file for changes every 30 seconds
# https://docs.rs/log4rs/0.8.3/log4rs/encode/pattern/index.html
refresh_rate: 30 seconds

appenders:
  stdout:
    kind: console
    encoder:
      pattern: "{d(%s.%f)} {l} [{h({t})}] {I}: {m}{n}"

  stdout_ref:
    kind: console
    encoder:
      pattern: "{f}:{L} {l} [{h({t})}] {I}: {m}{n}"

  logfile:
    kind: file
    path: "logs/output.log"
    encoder:
      pattern: "{d(%s.%f)} {l} [{h({t})}] {I}: {m}{n}"

  rolling_logfile:
    kind: rolling_file
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S.%f)} {l} [{h({t})}] {I}: {m}{n}"
    path: logs/output.log
    policy:
      kind: compound
      trigger:
        kind: size
        limit: 5 gb
      roller:
        kind: fixed_window
        pattern: 'logs/output_{}.log'
        base: 1
        count: 1

  tvm_logfile:
    kind: file
    path: "/ton-node/log/tvm.log"
    encoder:
      pattern: "{m}{n}"

root:
  level: error
  appenders:
    - rolling_logfile

loggers:
  # node messages
  ton_node:
    level: error
  boot:
    level: error
  sync:
    level: error

  # adnl messages
  adnl:
    level: error

  overlay:
    level: error

  rldp:
    level: error

  dht:
    level: error

  # block messages
  ton_block:
    level: error

  # block messages
  executor:
    level: error

  # tvm messages
  tvm:
    level: error

  librdkafka:
    level: error

  validator:
    level: error

  telemetry:
    level: error

  catchain:
    level: error

  validator_session:
    level: error
